### PR TITLE
Fix arista.eos.eos_acls replaced state for new ACEs

### LINKED ISSUE #296: eos.eos_acls replaced action producing incorrect commands
##### SUMMARY
The replaced action is not generating correct commands on ACLs to properly mutate existing ACLs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

` arista.eos.eos_acls`
##### ANSIBLE VERSION

```paste below
root@289224ebee40:/infrastructure/gee/ansible# ansible --version
ansible 2.10.15
  config file = /infrastructure/gee/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.9 (default, Feb  9 2021, 08:45:31) [GCC 8.3.0]
```

##### COLLECTION VERSION

```paste below
root@289224ebee40:/infrastructure/gee/ansible# ansible-galaxy collection list arista.eos

# /usr/local/lib/python3.7/site-packages/ansible_collections
Collection Version
---------- -------
arista.eos 1.0.3

# /root/.ansible/collections/ansible_collections
Collection Version
---------- -------
arista.eos 3.1.0
```

##### CONFIGURATION

```paste below
root@289224ebee40:/infrastructure/gee/ansible# ansible-config dump --only-changed

```

##### OS / ENVIRONMENT

localhost#show version
Arista cEOSLab

Software image version: 4.27.0F-24305004.4270F (engineering build)
##### STEPS TO REPRODUCE

EOS config:
```
localhost#show running-config | section test
ip access-list test1
   10 remark testing-eos-acl
   20 permit ospf 20.0.0.0/8 any
   30 permit ospf 30.0.0.0/8 any
ip access-list test2
   10 remark another-acl
   20 permit ip any any
```

```yaml
  - name: Replace device configuration with provided configuration
    arista.eos.eos_acls:
      config:
        - afi: ipv4
          acls:
            - name: test1
              aces:
                - sequence: 1
                  grant: permit
                  protocol: tcp
                  source:
                    subnet_address: 1.0.0.0/8
                  destination:
                    any: true
                - sequence: 2
                  grant: permit
                  protocol: tcp
                  source:
                    subnet_address: 2.0.0.0/8
                  destination:
                    any: true
                - sequence: 3
                  grant: permit
                  protocol: tcp
                  source:
                    subnet_address: 3.0.0.0/8
                  destination:
                    any: true
      state: replaced
    register: result

  - debug:
      var: result
```

##### EXPECTED RESULTS

The generated EOS commands to mutate the config should be:
```
        "commands": [
            "ip access-list test1",
            "no 10",
            "no 20",
            "no 30",
            "1 permit tcp 1.0.0.0/8 any"
            "2 permit tcp 2.0.0.0/8 any"
            "3 permit tcp 3.0.0.0/8 any"
        ],
```

##### ACTUAL RESULTS

Instead we get an incomplete set of commands (missing ACEs 2 and 3)
```paste below
        "commands": [
            "ip access-list test1",
            "no 10",
            "no 20",
            "no 30",
            "3 permit tcp 3.0.0.0/8 any"
        ],
```

### PR DESCRIPTION
**Pull request by dmahler**
##### SUMMARY

FIxes #296

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

arista.eos.eos_acls
##### ADDITIONAL INFORMATION

Refer to #296 for the same example
```paste below
# before
        "commands": [
            "ip access-list test1",
            "no 10",
            "no 20",
            "no 30",
            "3 permit tcp 3.0.0.0/8 any"
        ],

# after
        "commands": [
            "ip access-list test1",
            "no 10",
            "no 20",
            "no 30",
            "1 permit tcp 1.0.0.0/8 any",
            "2 permit tcp 2.0.0.0/8 any",
            "3 permit tcp 3.0.0.0/8 any"
        ],

```

### CODE REVIEW

**Comment by dmahler** [comment]
cc @GomathiselviS

**Comment by GomathiselviS** [comment]
@dmahler Thanks for working on this. Can you please add a unit testcase, which will cover the failure scenario?

**Comment by dmahler** [comment]
Unit test added @GomathiselviS

**Comment by dmahler** [comment]
```
root@27ac139fe617:~/.ansible/collections/ansible_collections/arista/eos/tests/unit/modules/network/eos# pytest -vv test_eos_acls.py  | grep '_replaced\|passed'
test_eos_acls.py::TestEosAclsModule::test_eos_acls_replaced PASSED       [ 90%]
test_eos_acls.py::TestEosAclsModule::test_eos_acls_replaced_idempotent PASSED [100%]
============================== 11 passed in 0.54s ==============================
```

**Review by GomathiselviS — APPROVED** [review]

**Comment by GomathiselviS** [comment]
Please run `tox -eblack` and `tox -elinters` from the collections folder, to avoid the failure of `ansible-tox-linters` job. This will fix the lint and format issues.

**Pull request merged**
