### PR TITLE
DNM

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1503

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
@GomathiselviS  why ansible-test-units-eos-python39 not running in your case?

**Comment by GomathiselviS** [comment]
> @GomathiselviS why ansible-test-units-eos-python39 not running in your case?

@ashwini-mhatre You can check the project-templates. It is not added there.

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request closed without merging**
