### PR TITLE
Fix  cleanup issues in integration tests

### LINKED ISSUE #234: Integration test run fails on python 2.7
##### SUMMARY

PR https://github.com/ansible-collections/ansible.netcommon/pull/289
```
2021-07-02 04:22:41.111940 \| centos-8 \| TASK [eos_vrf : Add Ethernet2 to vrf and check interface assigned state] *******
--
74196 | 2021-07-02 04:22:41.112321 \| centos-8 \| task path: /home/zuul/.ansible/collections/ansible_collections/arista/eos/tests/integration/targets/eos_vrf/tests/cli/basic.yaml:78
74197 | 2021-07-02 04:22:41.178670 \| centos-8 \| <199.19.213.79> attempting to start connection
74198 | 2021-07-02 04:22:41.179314 \| centos-8 \| <199.19.213.79> using connection plugin ansible.netcommon.network_cli
74199 | 2021-07-02 04:22:41.179642 \| centos-8 \| Found ansible-connection at path /home/zuul/venv/bin/ansible-connection
74200 | 2021-07-02 04:22:42.079453 \| centos-8 \| <199.19.213.79> found existing local domain socket, using it!
74201 | 2021-07-02 04:22:42.079787 \| centos-8 \| [WARNING]: Persistent connection logging is enabled for 199.19.213.79. This
74202 | 2021-07-02 04:22:42.079811 \| centos-8 \| will log ALL interactions to /home/zuul/ansible-debug.txt and WILL NOT redact
74203 | 2021-07-02 04:22:42.079825 \| centos-8 \| sensitive configuration like passwords. USE WITH CAUTION!
74204 | 2021-07-02 04:22:42.080116 \| centos-8 \| <199.19.213.79> updating play_context for connection
74205 | 2021-07-02 04:22:42.080932 \| centos-8 \| <199.19.213.79> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
74206 | 2021-07-02 04:22:42.081133 \| centos-8 \| <199.19.213.79> authorizing connection
74207 | 2021-07-02 04:22:42.081423 \| centos-8 \| <199.19.213.79>
74208 | 2021-07-02 04:22:42.081733 \| centos-8 \| <199.19.213.79> local domain socket path is /home/zuul/.ansible/pc/8b681bda45
74209 | 2021-07-02 04:22:42.085453 \| centos-8 \| redirecting (type: action) arista.eos.eos_vrf to arista.eos.eos
74210 | 2021-07-02 04:22:42.085923 \| centos-8 \| redirecting (type: action) arista.eos.eos_vrf to arista.eos.eos
74211 | 2021-07-02 04:22:42.086842 \| centos-8 \| [WARNING]: provider is unnecessary when using ansible.netcommon.network_cli and
74212 | 2021-07-02 04:22:42.086868 \| centos-8 \| will be ignored
74213 | 2021-07-02 04:22:42.087123 \| centos-8 \| <199.19.213.79> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
74214 | 2021-07-02 04:22:42.087391 \| centos-8 \| <199.19.213.79> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
74215 | 2021-07-02 04:22:42.088189 \| centos-8 \| <199.19.213.79> ESTABLISH LOCAL CONNECTION FOR USER: zuul
74216 | 2021-07-02 04:22:42.088486 \| centos-8 \| <199.19.213.79> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0 `"&& mkdir "` echo /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0/ansible-tmp-1625199762.0878391-45912-23972913986391 `" && echo ansible-tmp-1625199762.0878391-45912-23972913986391="` echo /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0/ansible-tmp-1625199762.0878391-45912-23972913986391 `" ) && sleep 0'
74217 | 2021-07-02 04:22:42.107502 \| centos-8 \| Using module file /home/zuul/.ansible/collections/ansible_collections/arista/eos/plugins/modules/eos_vrf.py
74218 | 2021-07-02 04:22:42.108848 \| centos-8 \| <199.19.213.79> PUT /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0/tmpsk8ghizn TO /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0/ansible-tmp-1625199762.0878391-45912-23972913986391/AnsiballZ_eos_vrf.py
74219 | 2021-07-02 04:22:42.110310 \| centos-8 \| <199.19.213.79> EXEC /bin/sh -c 'chmod u+x /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0/ansible-tmp-1625199762.0878391-45912-23972913986391/ /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0/ansible-tmp-1625199762.0878391-45912-23972913986391/AnsiballZ_eos_vrf.py && sleep 0'
74220 | 2021-07-02 04:22:42.122324 \| centos-8 \| <199.19.213.79> EXEC /bin/sh -c 'python /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0/ansible-tmp-1625199762.0878391-45912-23972913986391/AnsiballZ_eos_vrf.py && sleep 0'
74221 | 2021-07-02 04:22:54.762977 \| centos-8 \| <199.19.213.79> EXEC /bin/sh -c 'rm -f -r /home/zuul/.ansible/tmp/ansible-local-45396oibc_ob0/ansible-tmp-1625199762.0878391-45912-23972913986391/ > /dev/null 2>&1 && sleep 0'
74222 | 2021-07-02 04:22:54.778920 \| centos-8 \| fatal: [eos-4.20.10]: FAILED! => {
74223 | 2021-07-02 04:22:54.778958 \| centos-8 \|     "changed": false,
74224 | 2021-07-02 04:22:54.778974 \| centos-8 \|     "invocation": {
74225 | 2021-07-02 04:22:54.778988 \| centos-8 \|         "module_args": {
74226 | 2021-07-02 04:22:54.779000 \| centos-8 \|             "aggregate": null,
74227 | 2021-07-02 04:22:54.779013 \| centos-8 \|             "associated_interfaces": [
74228 | 2021-07-02 04:22:54.779025 \| centos-8 \|                 "Ethernet2"
74229 | 2021-07-02 04:22:54.779038 \| centos-8 \|             ],
74230 | 2021-07-02 04:22:54.779050 \| centos-8 \|             "delay": 10,
74231 | 2021-07-02 04:22:54.779062 \| centos-8 \|             "interfaces": [
74232 | 2021-07-02 04:22:54.779075 \| centos-8 \|                 "Ethernet2"
74233 | 2021-07-02 04:22:54.779087 \| centos-8 \|             ],
74234 | 2021-07-02 04:22:54.779099 \| centos-8 \|             "name": "test",
74235 | 2021-07-02 04:22:54.779111 \| centos-8 \|             "provider": null,
74236 | 2021-07-02 04:22:54.779123 \| centos-8 \|             "purge": false,
74237 | 2021-07-02 04:22:54.779135 \| centos-8 \|             "rd": "1:201",
74238 | 2021-07-02 04:22:54.779147 \| centos-8 \|             "state": "present"
74239 | 2021-07-02 04:22:54.779166 \| centos-8 \|         }
74240 | 2021-07-02 04:22:54.779192 \| centos-8 \|     },
74241 | 2021-07-02 04:22:54.779205 \| centos-8 \|     "msg": "Interface ethernet2 not configured on vrf test"
74242 | 2021-07-02 04:22:54.779225 \| centos-8 \| }
74243 | 2021-07-02 04:22:54.785994 \| centos-8 \|
74244 | 2021-07-02 04:22:54.786024 \| centos-8 \| PLAY RECAP *********************************************************************
74245 | 2021-07-02 04:22:54.786320 \| centos-8 \| eos-4.20.10                : ok=22   changed=6    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
##### SUMMARY

Fixes #234 

- The number of management interfaces differs across different target hosts. There is no point checking for the facts against a defined var, in cleanup tasks.

- The port channel configurations are not removed at the end of eos_lag interfaces test suite. This PR takes care of the cleanup.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Review by rohitthakur2590 — APPROVED** [review]
LGTM!

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
