### PR TITLE
eos_l2_interfaces : fix idempotent issue when allowed_vlans is set

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### SUMMARY

Fixes: #118 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
eos_l2_interfaces
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by agunnerson-ibm** [comment]
Thanks for working on this! Unfortunately, I think https://github.com/ansible-collections/arista.eos/pull/119/files?file-filters%5B%5D=.py&file-filters%5B%5D=.yaml#diff-17d25cd6bca5324cd8b49ab5310dd5cfR284-R287 does not work quite right for the `state: merged` case. For example:

Initial state:

```
interface Port-Channel1
   port-channel lacp fallback static
   port-channel lacp fallback timeout 60
   mlag 1
```

Ran:

```
- eos_l2_interfaces:
    config:
      - name: Port-Channel1
        mode: trunk
        trunk:
          trunk_allowed_vlans: 1-10
```

New state:

```
interface Port-Channel1
   switchport trunk allowed vlan 1-10
   switchport mode trunk
   port-channel lacp fallback static
   port-channel lacp fallback timeout 60
   mlag 1
```

Ran:

```
- eos_l2_interfaces:
    config:
      - name: Port-Channel1
        mode: trunk
        trunk:
          trunk_allowed_vlans: 1-10,21-30
```

New state:

```
interface Port-Channel1
   switchport trunk allowed vlan 21-30
   switchport mode trunk
   port-channel lacp fallback static
   port-channel lacp fallback timeout 60
   mlag 1
```

The `1-10` part is missing in the final state.

**Comment by agunnerson-ibm** [comment]
I have not tested all cases, but could it be fixed with this?
```
allowed_vlans = []
has_allowed_vlans = set()
want_allowed_vlans = set()

# ...

for con in [want, have]:
    expand_trunk_allowed_vlans(con)
want_allowed_vlans = want["trunk"].get("trunk_allowed_vlans")
if has_trunk:
    has_allowed_vlans = has_trunk.get("trunk_allowed_vlans")

if set(want_allowed_vlans.split(',')) != set(has_allowed_vlans.split(',')):
    commands.append(
        "switchport trunk allowed vlan {0}".format(want_allowed_vlans)
    )
```
Or alternatively, maybe
```
"switchport trunk allowed vlan {0}".format(allowed_vlans)
```
could be changed to
```
"switchport trunk allowed vlan add {0}".format(allowed_vlans)
```

**Comment by GomathiselviS** [comment]
> I have not tested all cases, but could it be fixed with this?
> 
> ```
> allowed_vlans = []
> has_allowed_vlans = set()
> want_allowed_vlans = set()
> 
> # ...
> 
> for con in [want, have]:
>     expand_trunk_allowed_vlans(con)
> want_allowed_vlans = want["trunk"].get("trunk_allowed_vlans")
> if has_trunk:
>     has_allowed_vlans = has_trunk.get("trunk_allowed_vlans")
> 
> if set(want_allowed_vlans.split(',')) != set(has_allowed_vlans.split(',')):
>     commands.append(
>         "switchport trunk allowed vlan {0}".format(want_allowed_vlans)
>     )
> ```
> 
> Or alternatively, maybe
> 
> ```
> "switchport trunk allowed vlan {0}".format(allowed_vlans)
> ```
> 
> could be changed to
> 
> ```
> "switchport trunk allowed vlan add {0}".format(allowed_vlans)
> ```

@agunnerson-ibm  Thanks for looking into this PR. I have added the `switchport trunk allowed vlan add ` command and the relevant testcase.

**Comment by agunnerson-ibm** [comment]
Thanks! The use case I mentioned above now works properly.

I have one more (philosophical) question: if the starting state is:
```
interface Port-Channel1
   switchport trunk allowed vlan 1-10,21-30
   switchport mode trunk
   port-channel lacp fallback static
   port-channel lacp fallback timeout 60
   mlag 1
```
and the following task is run:
```
- eos_l2_interfaces:
    config:
      - name: Port-Channel1
        mode: trunk
        trunk:
          trunk_allowed_vlans: 1-10
```
Should the result be:
```
switchport trunk allowed vlan 1-10
```
or
```
switchport trunk allowed vlan 1-10,21-30
```
for `state: merged`?

Right now, with this PR, it's the second.

**Comment by GomathiselviS** [comment]
> trunk_allowed_vlans: 1-10

@agunnerson-ibm :

No commands will be passed, since the vlans in the given config already exists in the device.

**Review by NilashishC — APPROVED** [review]

**Pull request merged**
