### PR TITLE
Modify acls module to generate argspec from DOCUMENTATION string

### PR DESCRIPTION
**Pull request by ganeshrn**
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/22

##### SUMMARY

*  Use the util function `convert_doc_to_module_argument_spec`
   defined in netcommon collection to generate agrspec at
   runtime from module documentation string.
   https://github.com/ansible-collections/ansible.netcommon/pull/22

*  Use YAML anchors for repeated options

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

eos_acls
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by gundalow** [comment]
Is this still needed, otherwise could it please be closed. Thanks!

**Comment by ganeshrn** [comment]
This feature will require changes in the facts module. That is facts module will need refactoring to implement as an action plugin. Closing the PR for now, we can revisit this feature after the facts module refactor is done.

**Pull request closed without merging**
