### PR TITLE
Make config modules work properly when module alias is used in task 

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/595

##### SUMMARY
- Module name will not always be prefixed with {{ network_os }}_.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
action/eos.py
eos_config.py

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
