### PR TITLE
Woah, we really should not be promoting provider for eAPI.

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

I also threw in the removal while I was in there. Feel free to argue about the date.

See also ansible-collections/cisco.nxos#77

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

doc_fragments/eos

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
