### PR TITLE
provide supported comment_token list

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rothakur@fedora.redhat.com>

##### SUMMARY

resolve: https://github.com/ansible-collections/arista.eos/issues/137

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by GomathiselviS — COMMENTED** [review]
@rohitthakur2590  The comment token for eos is '!!' . Can you please add a unit testcase to eos_config , to verify this fix?

**Comment by gundalow** [comment]
> @rohitthakur2590 The comment token for eos is '!!' . Can you please add a unit testcase to eos_config , to verify this fix?

@rohitthakur2590 Could you take a look at this please?

**Comment by trishnaguha** [comment]
@rohitthakur2590 @GomathiselviS Could you please update on this PR? Are we merging this?

**Comment by GomathiselviS** [comment]
@trishnaguha I shall look into this.

**Comment by jhg03a** [comment]
This PR appears to resolved instead by adding `!` to the [default comment tokens in netcommon](https://github.com/ansible-collections/ansible.netcommon/blob/321f4a7b8ede6bec0e64c7863600ba754eb8745a/plugins/module_utils/network/common/config.py#L37).

**Pull request closed without merging**
