### PR TITLE
Add unit testcases - eos_lag_interfaces

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### SUMMARY
Add unit testcases to eos_lag_interfaces RM

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
test_eos_lag_interfaces.py

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
