### PR TITLE
Update BGP neighbor peer group syntax

### PR DESCRIPTION
**Pull request by sc68cal**
Switch to new supported syntax

Part of #133

### CODE REVIEW

**Comment by sc68cal** [comment]
recheck

**Comment by GomathiselviS** [comment]
Hi @sc68cal Please use the full link for Depends-On.

**Comment by GomathiselviS** [comment]
recheck

**Comment by sc68cal** [comment]
@GomathiselviS I took a look at your edit but it doesn't appear that you changed anything? 

Screen Shot 2021-07-21 at 3 09 39 PM

**Comment by sc68cal** [comment]
Your edit doesn't appear to have changed anything, compared to what I added a couple hours ago

Screen Shot 2021-07-21 at 3 09 39 PM

**Comment by GomathiselviS** [comment]
> Your edit doesn't appear to have changed anything, compared to what I added a couple hours ago

When you click on 'edit', you will see the full link

```
Switch to new supported syntax

Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/960

Part of #133 

```

**Comment by sc68cal** [comment]
Ah ok. I see. Thanks. I have updated the other PR to fix that

**Comment by GomathiselviS** [comment]
recheck

**Review by GomathiselviS — APPROVED** [review]

**Pull request merged**
