### PR TITLE
Use regex to handle linkagg name

### LINKED ISSUE #79: eos_lag_interfaces name parameter requires 'Port-Channel' in the name despite documentation stating otherwise
The documentation for `eos_lag_interfaces` has examples such as

```
- name: Override all device configuration of all LAG attributes with provided configuration
  eos_lag_interfaces:
    config:
      - name: 10
        members:
          - member: Ethernet2
            mode: on
    state: overridden

```

However, the code that actually appears to implement this, uses the 12th letter of the `name` parameter, forward. 

https://github.com/ansible-collections/arista.eos/blob/9c38a1590ea031a6dbf3e4a93e40d0f04f319b57/plugins/module_utils/network/eos/config/lag_interfaces/lag_interfaces.py#L244

So following the documentation, you end up with an error because if you create a name of just `10` like the documentation states, `channel_id` turns into an empty string, which yields flawed commands and results in an error

```
ansible.module_utils.connection.ConnectionError: channel-group  mode on% Invalid input
```

Manaully fixing this by doing 

```
- name: Override all device configuration of all LAG attributes with provided configuration
  eos_lag_interfaces:
    config:
      - name: Port-Channel10
        members:
          - member: Ethernet2
            mode: on
    state: overridden
```

Corrects this issue.

### PR DESCRIPTION
**Pull request by sc68cal**
Fixes https://github.com/ansible-collections/arista.eos/issues/79

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by sc68cal** [comment]
@pabelanger thanks for tweaking the gate. Let me know if it's OK to delete the depends on from the cover message of this PR, didn't want to do it without asking.

**Comment by sc68cal** [comment]
@GomathiselviS updated, please re-review.

Also can you review #83

**Comment by sc68cal** [comment]
I'm going to look into creating a unit test

**Comment by sc68cal** [comment]
Still trying to figure out how to invoke the unit tests locally, I haven't found any documentation on how to run the unit tests and looking at the Zuul output it appears to be running an ansible playbook from somewhere else

**Comment by GomathiselviS** [comment]
@sc68cal Thanks for working on the unit tests. We appreciate your effort.

Please refer to this [link](https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html) , to get an idea on how to invoke unit tests locally, with various options.

To invoke the eos_lag_interfaces unit test you can use the following command, from your collections folder,
`ansible-test units tests/unit/modules/network/eos/test_eos_lag_interfaces.py  -vvv`

**Comment by sc68cal** [comment]
I found https://www.jeffgeerling.com/blog/2019/how-add-integration-tests-ansible-collection-ansible-test

**Comment by sc68cal** [comment]
Looks like the gate job never reported back? What do we need to do to re-start that job?

**Comment by sc68cal** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
