### PR TITLE
eos_bgp_global: Fix typo in argspec key

### LINKED ISSUE #206: eos_bgp_global state gathered fails if one neighboor is shutdown
##### SUMMARY
When I try to gather bgp config with module eos_bgp_global, if one neighboor is shutdown the playbook fail

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_bgp_global

##### ANSIBLE VERSION

```
ansible 2.10.8

```

##### STEPS TO REPRODUCE
When I try to gather bgp config with module eos_bgp_global, if all neighboor are enable it works fine : 

```
  - name: Use the bgp_global resource module to gather the current config
    eos_bgp_global:
      state: gathered
    register: bgp_global

```

If one neighboor is shutdown it fails with error message 
```
fatal: [hostname]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (basic.py) module: shutdown found in config -> neighbor. Supported parameters include: additional_paths, allowas_in, auto_local_addr, default_originate, description, dont_capability_negotiate, ebgp_multihop, encryption_password, enforce_first_as, export_localpref, fall_over, graceful_restart, graceful_restart_helper, idle_restart_timer, import_localpref, link_bandwidth, local_as, local_v6_addr, maximum_accepted_routes, maximum_received_routes, metric_out, monitoring, next_hop_self, next_hop_unchanged, next_hop_v6_address, out_delay, peer, peer_group, prefix_list, remote_as, remove_private_as, route_map, route_reflector_client, route_to_peer, send_community, shut_down, soft_recognition, timers, transport, ttl, update_source, weight"}
```

I think the problem is this line https://github.com/ansible-collections/arista.eos/blob/ef6f78ff7e40c09418730be96c11d2155b231073/plugins/modules/eos_bgp_global.py#L562 it should be shutdown and not shut_down

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### SUMMARY

Fixes #206 
This PR also takes care of improving the test coverage for eos_bgp_global module.

##### ISSUE TYPE

- Bugfix Pull Request
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by rohitthakur2590 — APPROVED** [review]

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
