### PR TITLE
Add whitespace to 'snmp vrf' command

### LINKED ISSUE #487: eos_snmp_server
##### SUMMARY

rendered configuration is incorrect for Arista EOS version 4.28.4M 
1. under user config line - no space between vrf & vrf name var --> snmp-server host 'hostip' vrf'vrfname' version 3 priv 'user'
        should be-> snmp-server host 'hostip' vrf 'vrfname' version 3 priv 'user
3. under host config line - omits keyword auth -> snmp-server user user1 group1 v3  sha sha-pass priv aes aes-pass
        should be-> snmp-server user 'user1' 'group1' v3 auth sha 'sha-pass' priv aes 'aes-pass'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

arista.eos.eos_snmp_server

##### ANSIBLE VERSION

```paste below
Ansible version 2.13.7
```

##### COLLECTION VERSION

community.general 2.5.1

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Arista EOS 4.28.4M

##### STEPS TO REPRODUCE

---
- name: Configure SNMPv3 on Arista EOS Switches
  hosts: veos
  tasks:
    - name: Set SNMPv3 parameters vrf mgmt VRF
      arista.eos.eos_snmp_server:
        config:
          contact: "admin"
          location: "location1"
          vrfs: 
            - vrf: "management"
              local_interface: "Management1"
          groups:
            - group: "group1"
              auth_privacy: "priv"
              version: "v3"
          users:
            - user: "user1"
              group:  "group1"
              version: "v3"
              auth: 
                algorithm: "sha"
                auth_passphrase: "shaPassword1"
                encryption: "aes"
                priv_passphrase: "aesPassphrase123"
          hosts:
            - host: "10.10.10.11"
              vrf: "management"
              version: "3 priv"
              user: "user1"
            - host: "10.10.10.10"
              vrf: "management"
              version: "3 priv"
              user: "user1"   
    - name: Save configuration
      arista.eos.eos_command:
        commands:
          - "write memory"

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by TheRealBecks**
##### SUMMARY

- A whitespace was missing in string concatenation
- In two functions the partial command `auth` was missing
##### ISSUE TYPE

* Bugfix Pull Request (Fixes #487)

##### COMPONENT NAME
eos_snmp_server

### CODE REVIEW

**Comment by TheRealBecks** [comment]
I added a changelog and a missing `auth` string in SNMP.

@rohitthakur2590 An updated test case is still missing. Is there a documentation that I can use to get the knowledge to update the test cases?

**Comment by rohitthakur2590** [comment]
@TheRealBecks  Unfortunately there isn't a detailed documentation regarding testing, but you can add a unit tests in this file https://github.com/ansible-collections/arista.eos/blob/main/tests/unit/modules/network/eos/test_eos_snmp_server.py

**Comment by TheRealBecks** [comment]
@rohitthakur2590 I don't know why but I can't run tests with this repository due to import issues, so I'm not able to provide updated unit test files for any of my PRs :unamused: Could you be so kind and provide me the updated files for the PRs once again?

I will try to fix the import issues within the next few days, so I can fix the next Prs myself.

**Review by rohitthakur2590 — APPROVED** [review]

**Comment by TheRealBecks** [comment]
@rohitthakur2590 What is the check `ack / ack / ack (pull_request_target)` that fails? Do I have to do something?

**Comment by rohitthakur2590** [comment]
> @rohitthakur2590 What is the check `ack / ack / ack (pull_request_target)` that fails? Do I have to do something?

that was asking for a valid label. Everything was good at your end!

**Pull request merged**
