### PR TITLE
[eos]: Fix Sanity tests

### PR DESCRIPTION
**Pull request by GomathiselviS**
Depends-On: https://github.com/ansible/ansible/pull/70015
Depends-On: https://github.com/ansible/ansible/pull/69935

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### SUMMARY
This PR fixes the eos sanity test failures.

Command used :  ansible-test sanity --python 3.6

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
